
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_TMG399X_NEW),y)
obj-y	+=  tmg399x-new/
endif

ifeq ($(CONFIG_MTK_EPL8865_NEW),y)
obj-y	+=  epl8865-new/
endif

